"""
RuleKit contract: DeterminationProgram.

The top-level artifact a producer ships. Contains the DAG (as a
registry of nodes keyed by NodeId), the Map spec (atom catalog plus
extraction policy), the case input schema, the test suite, the named
numeric constants, and metadata about the program and its production.

Domain-agnostic. The program object does not reference a policy text,
a reader voice, or the build process that may have produced it. A
program may have been hand-authored, generated by an LLM-driven
build, translated from another format, or composed from fragments —
the contract treats them identically.

This module assembles the discriminated union over all node types and
defines the DeterminationProgram model itself.
"""
from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from rulekit.contract.base import AtomId, NodeId, NodeRef
from rulekit.contract.boolean import (
    AndNodeSpec,
    AtLeastNodeSpec,
    AtomRef,
    ComparisonSpec,
    NotNodeSpec,
    OrNodeSpec,
)
from rulekit.contract.cases import CaseInputSchema, TestCase
from rulekit.contract.map import MapSpec
from rulekit.contract.numeric import (
    BinaryArithmeticSpec,
    ConditionalNumericSpec,
    ConstantSpec,
    NamedQuantitySpec,
    NumericAtomRef,
    UnaryArithmeticSpec,
    VariadicArithmeticSpec,
)


# ---------------------------------------------------------------------------
# Discriminated union over all node types
# ---------------------------------------------------------------------------

# Pydantic v2 idiom: `Annotated[Union[...], Field(discriminator="kind")]`
# tells Pydantic to look at the `kind` field of incoming JSON to choose
# which member of the union to deserialize into. Without this, Pydantic
# would try each member in turn — which both succeeds incorrectly (the
# first compatible match wins) and produces unhelpful errors.
#
# The discriminator value on each class is set as a Literal default in
# that class's `kind: Literal[...] = "..."` declaration. The union below
# enumerates every node type the registry can hold; adding a new node
# type means adding it here and giving the new class a unique `kind`.
AnyNodeSpec = Annotated[
    Union[
        # Boolean-valued nodes
        AtomRef,
        AndNodeSpec,
        OrNodeSpec,
        NotNodeSpec,
        AtLeastNodeSpec,
        ComparisonSpec,
        # Numeric-valued nodes
        NumericAtomRef,
        ConstantSpec,
        UnaryArithmeticSpec,
        BinaryArithmeticSpec,
        VariadicArithmeticSpec,
        ConditionalNumericSpec,
        NamedQuantitySpec,
    ],
    Field(discriminator="kind"),
]


# Tag sets used by validators.py to check that a NodeRef points to a
# node of the right value-type. Boolean-valued nodes can sit where a
# child of And/Or/Not/AtLeast or a condition of ConditionalNumeric is
# expected. Numeric-valued nodes can sit where a child of arithmetic
# or a branch of ConditionalNumeric or an operand of Comparison is
# expected.
BOOLEAN_NODE_KINDS = frozenset({
    "atom_ref", "and", "or", "not", "at_least", "comparison",
})
NUMERIC_NODE_KINDS = frozenset({
    "numeric_atom_ref", "constant",
    "unary_arithmetic", "binary_arithmetic", "variadic_arithmetic",
    "conditional_numeric", "named_quantity",
})


# ---------------------------------------------------------------------------
# Determinations
# ---------------------------------------------------------------------------

class DeterminationSpec(BaseModel):
    """A named determination — the root claim the engine adjudicates.

    `composition`:
        "derived"     - the determination has its own root_node in the
                        program's node registry. Most determinations
                        are derived.
        "complement"  - this determination is structurally NOT(other).
                        `linked_to` names the other determination;
                        evaluation is NOT(linked_to.root_node).
                        Common for approve/deny pairs.

    Exactly one of (root_node, linked_to) is set, matching the
    composition. Enforced by the model_validator below.
    """
    model_config = ConfigDict(extra="forbid")

    id: AtomId
    description: str = Field(min_length=1)
    polarity: Literal["positive", "negative", "neutral"] = "neutral"
    source_span: str = ""
    composition: Literal["derived", "complement"] = "derived"
    root_node: Optional[NodeRef] = None
    linked_to: Optional[AtomId] = None

    def model_post_init(self, __context):
        # Pydantic v2 doesn't run model_validator(mode="after") inside
        # nested-model construction reliably with the field annotations
        # we use, so we do the composition check in post_init where it
        # always fires.
        if self.composition == "derived":
            if self.root_node is None or self.linked_to is not None:
                raise ValueError(
                    f"determination {self.id!r}: composition=derived "
                    f"requires root_node set and linked_to unset"
                )
        elif self.composition == "complement":
            if self.linked_to is None or self.root_node is not None:
                raise ValueError(
                    f"determination {self.id!r}: composition=complement "
                    f"requires linked_to set and root_node unset"
                )


# ---------------------------------------------------------------------------
# Program metadata and production record
# ---------------------------------------------------------------------------

class ProgramMetadata(BaseModel):
    """Identification and free-form description.

    Domain-agnostic. The contract does not interpret these fields; they
    are for human consumption and for the producer's own bookkeeping.
    `extras` is a producer-defined free-form dict — useful for shipping
    domain conventions (which abbreviation a producer chose, which
    reader voice was used) without making the contract know about
    them.
    """
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    version: str = Field(min_length=1)
    description: str = ""
    extras: dict[str, Any] = Field(default_factory=dict)


class ProductionRecord(BaseModel):
    """Provenance for the program itself.

    Distinguishes "who built this and when" from "where the source
    material lives" (the latter is producer-domain-specific and lives
    in `metadata.extras` if the producer wants to record it).
    """
    model_config = ConfigDict(extra="forbid")

    produced_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    produced_by: str = "unknown"
    source_revision: str = ""
    decisions: list[str] = Field(default_factory=list)
    deferred: list[str] = Field(default_factory=list)
    tested: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# The top-level program
# ---------------------------------------------------------------------------

class DeterminationProgram(BaseModel):
    """The complete artifact a producer ships.

    Everything needed to adjudicate cases under one set of
    determinations: the DAG, the Map spec, the case input schema,
    and the test suite, plus identification and production
    provenance.

    Constants are program-scope, not per-node-scope, so that the same
    named constant can be referenced from multiple ConstantSpec or
    UnaryArithmeticSpec nodes without redeclaration.

    Cross-program validation (atom-ref integrity, DAG acyclicity,
    test-case conformance, etc.) is implemented in
    rulekit.contract.validators and is invoked by callers via
    `validate_program(program)`. The model itself runs only the
    field-level and model-level validators defined on the
    sub-models.
    """
    model_config = ConfigDict(extra="forbid")

    contract_version: Literal["1.0"] = "1.0"
    metadata: ProgramMetadata
    constants: dict[str, Decimal] = Field(default_factory=dict)
    nodes: dict[NodeId, AnyNodeSpec] = Field(default_factory=dict)
    map_spec: MapSpec = Field(default_factory=MapSpec)
    determinations: dict[AtomId, DeterminationSpec] = Field(default_factory=dict)
    case_input_schema: CaseInputSchema = Field(default_factory=CaseInputSchema)
    test_cases: list[TestCase] = Field(default_factory=list)
    production_record: ProductionRecord = Field(default_factory=ProductionRecord)


__all__ = [
    "AnyNodeSpec",
    "BOOLEAN_NODE_KINDS",
    "NUMERIC_NODE_KINDS",
    "DeterminationSpec",
    "ProgramMetadata",
    "ProductionRecord",
    "DeterminationProgram",
]
